`timescale 1ns/1ps
// =============================================================================
// frame_input_if.sv                                    (ICD v3 — INPUT SIDE)
//
// THE input interface file.  Everything the SHAKTI side writes INTO the IP
// lives here: the AXI4-Lite write channels, the complete register write
// decode, the 320×240 frame buffer BRAM, the RGB565 camera upload protocol
// (including hardware un-flip and grayscale conversion), the on-the-fly 4×
// decimator, and the two pixel-feed engines (KCF crop feed and target-
// designation template build).  A collaborator modelling the SoC→IP
// direction needs only this file.
//
// ── Upload protocol (ICD v3 §3) ────────────────────────────────────────────
//   * Camera format: ArduCAM "BMP" mode — 320×240 RGB565, 2 bytes/pixel
//     HIGH BYTE FIRST, sensor flip+mirror → the stream arrives BOTTOM-RIGHT
//     first (scanning right→left, bottom→top).
//   * IMAGE_FRAME (0x28), write-only: TWO RGB565 pixels per 32-bit write,
//     exactly as the byte stream lands in a little-endian word:
//       pixel_a = {wdata[ 7:0], wdata[15: 8]}   (arrives first)
//       pixel_b = {wdata[23:16], wdata[31:24]}
//     BUF_IDX advances by 2 per accepted write.
//   * One frame = 320×240 = 76,800 pixels = 38,400 writes.
//   * Hardware converts RGB565 → 8-bit grayscale (BT.601: 77R+150G+29B >> 8)
//     and UN-FLIPS the scan: stored frame and ALL coordinates (TARGET_POS,
//     ABS_ROW/COL) are upright — row 0 top, col 0 left.  Software must not
//     convert or reorder anything.
//   * BUF_IDX (0x30): write 0 before every frame (resets position + decimator
//     accumulators).  Value 76,800 = frame complete (replaces TLAST).
//     Only the values 0 and 76,800 are supported for writes.
//   * Pixel writes while busy=1, or that would pass 76,800, are ACKed OKAY
//     on AXI and silently discarded.
//   * TARGET_POS (0x2C): {col[24:16], row[8:0]} — designation centre used by
//     CTRL.target_init; clamped to row [32, 208], col [32, 288].
//
// ── Storage owned here ────────────────────────────────────────────────────
//   frame_buf : 38,400 × 16-bit BRAM  (320×240 gray pixels, 2 per word,
//                                      odd pixel index in the high byte)
//   dec_buf   :  4,800 ×  8-bit BRAM  (80×60, 4×4-mean decimated copy,
//                                      built on the fly during upload)
//   tmpl_buf  :    256 ×  8-bit       (16×16 decimated target template)
//   + template mean and energy Et = Σ(t−mean)² for the NCC search
//
// ── Engines ────────────────────────────────────────────────────────────────
//   crop feed : on crop_req(centre) streams the full-res 64×64 crop
//               (row-major) into kcf_top's patch write port (~4.1K cycles)
//   tinit     : same crop pass at TARGET_POS; simultaneously builds the
//               decimated zero-mean NCC template, then a 256-cycle energy
//               pass computes Et
// =============================================================================

module frame_input_if #(
    parameter FRAME_W    = 320,
    parameter FRAME_H    = 240,
    parameter PATCH_N    = 64,
    parameter DEC        = 4,
    parameter DATA_WIDTH = 16,
    parameter ADDR_WIDTH = 32,
    // Preloaded designation (ICD v3.1): the designation frame is baked into
    // the frame BRAM at configuration, and TARGET_POS resets to the baked
    // target centre — generated by scripts/gen_target_mem.py
    parameter TARGET_MEM = "target_frame.mem",
    parameter [8:0] TGT_ROW = 9'd72,   // watch dial row
    parameter [8:0] TGT_COL = 9'd136  // watch dial col
)(
    input  wire                     clk,
    input  wire                     rst_n,

    // ── AXI4-Lite write address channel ────────────────────────────────
    input  wire [ADDR_WIDTH-1:0]    s_axi_awaddr,
    input  wire                     s_axi_awvalid,
    output reg                      s_axi_awready,

    // ── AXI4-Lite write data channel ───────────────────────────────────
    input  wire [31:0]              s_axi_wdata,
    input  wire [3:0]               s_axi_wstrb,
    input  wire                     s_axi_wvalid,
    output reg                      s_axi_wready,

    // ── AXI4-Lite write response channel ────────────────────────────────
    output reg  [1:0]               s_axi_bresp,
    output reg                      s_axi_bvalid,
    input  wire                     s_axi_bready,

    // ── Config values (to core + read-back by result_output_if) ────────
    output reg  [1:0]               mode,
    output reg  signed [DATA_WIDTH-1:0] thresh,
    output reg  signed [DATA_WIDTH-1:0] kcf_thresh,   // loss thr; 0 = disabled
    output reg  signed [DATA_WIDTH-1:0] lambda,
    output reg  [8:0]               target_row,
    output reg  [8:0]               target_col,
    output reg                      irq_mask,       // reserved v1 semantics
    output reg                      irq_pending,    // W1C here, set by irq_set
    input  wire                     irq_set,

    // ── Command flags (to track_ctrl) ──────────────────────────────────
    output reg                      start_pend,
    output reg                      tinit_pend,
    output reg                      sreset_pulse,
    input  wire                     start_consume,
    input  wire                     tinit_consume,

    // ── Frame status ────────────────────────────────────────────────────
    output wire                     frame_complete,
    output reg  [16:0]              buf_idx,
    input  wire                     busy,           // stat_busy: drop pixels

    // ── Decimated-frame read port (ncc_search) ─────────────────────────
    input  wire [12:0]              dec_rd_addr,
    output reg  [7:0]               dec_rd_data,    // 1-cycle latency

    // ── Template read port (ncc_search) ────────────────────────────────
    input  wire [7:0]               tmpl_rd_addr,
    output wire signed [8:0]        tmpl_rd_data,   // t − mean, 1-cycle latency
    output reg  [25:0]              tmpl_energy,    // Et

    // ── Crop feed engine (track_ctrl) ──────────────────────────────────
    input  wire                     crop_req,       // pulse; centre pre-clamped
    input  wire [8:0]               crop_row,
    input  wire [8:0]               crop_col,
    output reg                      crop_done,      // pulse

    // ── Template-init engine (track_ctrl) ──────────────────────────────
    input  wire                     tinit_req,      // pulse; uses TARGET_POS
    output reg                      tinit_done,     // pulse

    // ── KCF patch write port (to kcf_top) ──────────────────────────────
    output reg  [11:0]              kcf_patch_addr,
    output reg  signed [DATA_WIDTH-1:0] kcf_patch_data,
    output reg                      kcf_patch_wr_en
);

    localparam FRAME_PIXELS = FRAME_W * FRAME_H;          // 76,800
    localparam FRAME_WORDS  = FRAME_PIXELS / 2;           // 38,400 (2 px/word)
    localparam DEC_W        = FRAME_W / DEC;              // 80
    localparam DEC_H        = FRAME_H / DEC;              // 60
    localparam TMPL_W       = PATCH_N / DEC;              // 16
    localparam C_MIN        = PATCH_N/2;                  // 32
    localparam C_MAX_R      = FRAME_H - PATCH_N/2;        // 208
    localparam C_MAX_C      = FRAME_W - PATCH_N/2;        // 288

    // Register slots — addr[5:2] (ICD: 16 word slots, 0x00–0x3C)
    localparam REG_CTRL       = 4'd0;    // 0x00
    localparam REG_MODE       = 4'd1;    // 0x04
    localparam REG_THRESH     = 4'd2;    // 0x08
    localparam REG_LAMBDA     = 4'd3;    // 0x0C
    localparam REG_IRQ_MASK   = 4'd8;    // 0x20 (reserved)
    localparam REG_IRQ_STAT   = 4'd9;    // 0x24 (reserved, W1C)
    localparam REG_IMAGE_FRM  = 4'd10;   // 0x28
    localparam REG_TARGET_POS = 4'd11;   // 0x2C
    localparam REG_BUF_IDX    = 4'd12;   // 0x30
    localparam REG_KCF_THRESH = 4'd13;   // 0x34

    assign frame_complete = (buf_idx == FRAME_PIXELS[16:0]);

    // ════════════════════════════════════════════════════════════════════
    //  Frame buffer BRAM — 38,400 × 16-bit gray (2 pixels/word).
    //  The camera scan is bottom-right-first; each accepted write lands the
    //  two converted pixels as ONE descending-addressed word, so the stored
    //  image is upright.  Word w = {gray(2w+1), gray(2w)} (odd px = high byte)
    // ════════════════════════════════════════════════════════════════════
    (* ram_style = "block" *) reg [15:0] frame_buf [0:FRAME_WORDS-1];
    reg [15:0] frame_rd_word;
    reg        frame_we;
    reg [15:0] frame_waddr;
    reg [15:0] frame_wdata;
    wire [15:0] frame_raddr;             // from the crop/tinit engine

    // Designation frame preload — BRAM initialised from the bitstream so the
    // boot-time auto-designation can crop/train before any camera upload
    initial $readmemh(TARGET_MEM, frame_buf);

    always @(posedge clk) begin
        if (frame_we) frame_buf[frame_waddr] <= frame_wdata;
        frame_rd_word <= frame_buf[frame_raddr];
    end

    // ════════════════════════════════════════════════════════════════════
    //  Decimated frame BRAM — 4,800 × 8 (80×60)
    // ════════════════════════════════════════════════════════════════════
    (* ram_style = "block" *) reg [7:0] dec_buf [0:DEC_W*DEC_H-1];
    reg        dec_we;
    reg [12:0] dec_waddr;
    reg [7:0]  dec_wdata;

    always @(posedge clk) begin
        if (dec_we) dec_buf[dec_waddr] <= dec_wdata;
        dec_rd_data <= dec_buf[dec_rd_addr];
    end

    // ════════════════════════════════════════════════════════════════════
    //  Upload position tracking (DESCENDING — camera scan order) +
    //  on-the-fly 4×4 decimator
    // ════════════════════════════════════════════════════════════════════
    reg [8:0]  srow;                     // arriving row, 239 → 0
    reg [8:0]  scol;                     // arriving col (odd of pair), 319 → 1
    reg [11:0] dacc [0:DEC_W-1];         // 80 block-column accumulators
    integer di;

    // ── RGB565 → 8-bit grayscale (BT.601 weights, 77+150+29 = 256) ─────
    function [7:0] rgb565_gray;
        input [15:0] px;
        reg [7:0] r8, g8, b8;
        reg [15:0] acc;
        begin
            r8 = {px[15:11], px[15:13]};
            g8 = {px[10:5],  px[10:9]};
            b8 = {px[4:0],   px[4:2]};
            acc = 8'd77*r8 + 8'd150*g8 + 8'd29*b8;
            rgb565_gray = acc[15:8];
        end
    endfunction

    // ════════════════════════════════════════════════════════════════════
    //  Template storage — 256 × 8 raw + mean + energy
    // ════════════════════════════════════════════════════════════════════
    reg [7:0]  tmpl_buf [0:TMPL_W*TMPL_W-1];
    reg        tmpl_we;
    reg [7:0]  tmpl_waddr_r, tmpl_wdata_r;
    reg [7:0]  tmpl_mean;
    reg [7:0]  tmpl_rd_raw;
    wire [7:0] tmpl_raddr_mux;           // engine (energy pass) or ncc_search

    always @(posedge clk) begin
        if (tmpl_we) tmpl_buf[tmpl_waddr_r] <= tmpl_wdata_r;
        tmpl_rd_raw <= tmpl_buf[tmpl_raddr_mux];
    end

    // Zero-mean output (subtract after the read register — still 1-cycle)
    assign tmpl_rd_data = $signed({1'b0, tmpl_rd_raw}) - $signed({1'b0, tmpl_mean});

    // ════════════════════════════════════════════════════════════════════
    //  Crop / template-init engine
    // ════════════════════════════════════════════════════════════════════
    localparam E_IDLE   = 2'd0;
    localparam E_STREAM = 2'd1;   // 4096-pixel crop pass
    localparam E_ENERGY = 2'd2;   // 256-cycle Et pass (tinit only)

    reg [1:0]  eng_state;
    reg        eng_is_tinit;
    reg [8:0]  eng_top, eng_left;        // crop top-left (full-res)
    reg [12:0] eng_k;                    // 0..4096 issue counter
    reg [11:0] eng_k_d;                  // data-phase index
    reg        eng_k_v;
    reg        eng_lane_d;               // byte lane (pixel addr bit 0)
    reg [11:0] tacc  [0:TMPL_W-1];       // 16 template block accumulators
    reg [19:0] tsum;                     // Σ crop pixels (for mean)
    reg [8:0]  e_i;                      // energy pass counter
    reg [8:0]  e_i_d;
    reg        e_i_v;
    reg [25:0] et_acc;

    // Engine pixel address (full-res): (top + k[11:6]) * 320 + (left + k[5:0])
    wire [8:0]  eng_r    = eng_top  + {3'd0, eng_k[11:6]};
    wire [8:0]  eng_c    = eng_left + {3'd0, eng_k[5:0]};
    wire [16:0] eng_addr = ({8'd0, eng_r} << 8) + ({8'd0, eng_r} << 6)
                         + {8'd0, eng_c};
    assign frame_raddr = eng_addr[16:1];   // 2 pixels per 16-bit word

    // Byte-lane select on the registered word (data phase):
    // odd pixel index = high byte, even = low byte
    wire [7:0] eng_pix = eng_lane_d ? frame_rd_word[15:8]
                                    : frame_rd_word[7:0];

    // Template read mux: energy pass owns the port during E_ENERGY
    assign tmpl_raddr_mux = (eng_state == E_ENERGY) ? e_i[7:0] : tmpl_rd_addr;

    // Energy-pass operand (zero-mean, signed)
    wire signed [8:0]  e_diff = $signed({1'b0, tmpl_rd_raw})
                              - $signed({1'b0, tmpl_mean});
    wire [17:0]        e_sq   = e_diff * e_diff;

    // TARGET_POS clamped for the tinit crop (per-axis limits: 320×240 frame)
    wire [8:0] t_row_cl = (target_row < C_MIN[8:0])   ? C_MIN[8:0]
                        : (target_row > C_MAX_R[8:0]) ? C_MAX_R[8:0] : target_row;
    wire [8:0] t_col_cl = (target_col < C_MIN[8:0])   ? C_MIN[8:0]
                        : (target_col > C_MAX_C[8:0]) ? C_MAX_C[8:0] : target_col;

    integer ti;

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            eng_state       <= E_IDLE;
            eng_is_tinit    <= 1'b0;
            eng_top         <= 9'd0;
            eng_left        <= 9'd0;
            eng_k           <= 13'd0;
            eng_k_d         <= 12'd0;
            eng_k_v         <= 1'b0;
            eng_lane_d      <= 2'd0;
            tsum            <= 20'd0;
            tmpl_mean       <= 8'd0;
            tmpl_energy     <= 26'd0;
            et_acc          <= 26'd0;
            e_i             <= 9'd0;
            e_i_d           <= 9'd0;
            e_i_v           <= 1'b0;
            crop_done       <= 1'b0;
            tinit_done      <= 1'b0;
            kcf_patch_addr  <= 12'd0;
            kcf_patch_data  <= {DATA_WIDTH{1'b0}};
            kcf_patch_wr_en <= 1'b0;
            tmpl_we         <= 1'b0;
            tmpl_waddr_r    <= 8'd0;
            tmpl_wdata_r    <= 8'd0;
            for (ti = 0; ti < TMPL_W; ti = ti + 1)
                tacc[ti] <= 12'd0;
        end else begin
            crop_done       <= 1'b0;
            tinit_done      <= 1'b0;
            kcf_patch_wr_en <= 1'b0;
            tmpl_we         <= 1'b0;

            case (eng_state)

                E_IDLE: begin
                    if (crop_req || tinit_req) begin
                        eng_is_tinit <= tinit_req;
                        eng_top      <= (tinit_req ? t_row_cl : crop_row) - C_MIN[8:0];
                        eng_left     <= (tinit_req ? t_col_cl : crop_col) - C_MIN[8:0];
                        eng_k        <= 13'd0;
                        eng_k_v      <= 1'b0;
                        tsum         <= 20'd0;
                        for (ti = 0; ti < TMPL_W; ti = ti + 1)
                            tacc[ti] <= 12'd0;
                        eng_state    <= E_STREAM;
                    end
                end

                // ── Stream the 64×64 crop: 1 pixel/cycle, 1-cycle read lat ─
                E_STREAM: begin
                    if (eng_k < 13'd4096)
                        eng_k <= eng_k + 13'd1;
                    eng_k_d    <= eng_k[11:0];
                    eng_lane_d <= eng_addr[1:0];
                    eng_k_v    <= (eng_k < 13'd4096);

                    if (eng_k_v) begin
                        // Feed KCF patch port (Q8.8 zero-extended pixel)
                        kcf_patch_addr  <= eng_k_d;
                        kcf_patch_data  <= {{(DATA_WIDTH-8){1'b0}}, eng_pix};
                        kcf_patch_wr_en <= 1'b1;

                        // Template build (tinit only): 4×4 block averaging
                        if (eng_is_tinit) begin
                            tsum <= tsum + {12'd0, eng_pix};
                            if (eng_k_d[7:6] == 2'd3 && eng_k_d[1:0] == 2'd3) begin
                                // Block complete → write mean of 16 pixels
                                tmpl_we      <= 1'b1;
                                tmpl_waddr_r <= {eng_k_d[11:8], eng_k_d[5:2]};
                                tmpl_wdata_r <= (tacc[eng_k_d[5:2]]
                                                 + {4'd0, eng_pix}) >> 4;
                                tacc[eng_k_d[5:2]] <= 12'd0;
                            end else begin
                                tacc[eng_k_d[5:2]] <= tacc[eng_k_d[5:2]]
                                                    + {4'd0, eng_pix};
                            end
                        end

                        if (eng_k_d == 12'd4095) begin
                            eng_k_v <= 1'b0;
                            if (eng_is_tinit) begin
                                // Template values are 4×4-block means, so
                                // tmpl mean = (Σ all crop pixels) / 4096
                                // (tsum has not yet absorbed this last pixel)
                                tmpl_mean <= (tsum + {12'd0, eng_pix}) >> 12;
                                e_i       <= 9'd0;
                                e_i_v     <= 1'b0;
                                et_acc    <= 26'd0;
                                eng_state <= E_ENERGY;
                            end else begin
                                crop_done <= 1'b1;
                                eng_state <= E_IDLE;
                            end
                        end
                    end
                end

                // ── Template energy pass: Et = Σ(t−mean)², 256 entries ────
                E_ENERGY: begin
                    if (e_i < 9'd256)
                        e_i <= e_i + 9'd1;
                    e_i_d <= e_i;
                    e_i_v <= (e_i < 9'd256);

                    if (e_i_v) begin
                        et_acc <= et_acc + {8'd0, e_sq};
                        if (e_i_d == 9'd255) begin
                            tmpl_energy <= et_acc + {8'd0, e_sq};
                            tinit_done  <= 1'b1;
                            e_i_v       <= 1'b0;
                            eng_state   <= E_IDLE;
                        end
                    end
                end

                default: eng_state <= E_IDLE;

            endcase
        end
    end

    // ════════════════════════════════════════════════════════════════════
    //  AXI4-Lite write path — registers, packed pixel upload, decimator
    // ════════════════════════════════════════════════════════════════════
    reg [ADDR_WIDTH-1:0]  aw_addr_lat;
    reg                   aw_pend;
    reg [31:0]            w_data_lat;
    reg                   w_pend;

    // RGB565 pixel pair from the data latch (camera bytes H0 L0 H1 L1 in a
    // little-endian word: pixel_a = first-arriving = bottom-right-most)
    wire [15:0] wpx_a  = {w_data_lat[7:0],   w_data_lat[15:8]};
    wire [15:0] wpx_b  = {w_data_lat[23:16], w_data_lat[31:24]};
    wire [7:0]  wgray_a = rgb565_gray(wpx_a);   // odd upright index → high byte
    wire [7:0]  wgray_b = rgb565_gray(wpx_b);   // even upright index → low byte
    wire [9:0]  wsum2  = {2'd0, wgray_a} + {2'd0, wgray_b};
    wire [6:0]  wbc    = scol[8:2];             // block column 0..79
    wire [12:0] wdec_addr = ({6'd0, srow[8:2]} << 6)
                          + ({6'd0, srow[8:2]} << 4)
                          + {6'd0, wbc};
    // Un-flip: stream pixel pair j lands at descending word FRAME_WORDS-1-j
    wire [15:0] wword_addr = FRAME_WORDS[15:0] - 16'd1 - buf_idx[16:1];
    wire        pix_accept = !busy &&
                             (buf_idx <= FRAME_PIXELS[16:0] - 17'd2);

    always @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            s_axi_awready <= 1'b0;
            s_axi_wready  <= 1'b0;
            s_axi_bvalid  <= 1'b0;
            s_axi_bresp   <= 2'b00;
            aw_addr_lat   <= {ADDR_WIDTH{1'b0}};
            aw_pend       <= 1'b0;
            w_data_lat    <= 32'd0;
            w_pend        <= 1'b0;
            mode          <= 2'd0;
            thresh        <= 16'sh0080;
            kcf_thresh    <= 16'sh0000;    // loss fallback disabled by default
            lambda        <= 16'sh0001;
            target_row    <= TGT_ROW;      // baked designation centre
            target_col    <= TGT_COL;
            irq_mask      <= 1'b0;         // v2 poll mode
            irq_pending   <= 1'b0;
            start_pend    <= 1'b0;
            tinit_pend    <= 1'b0;
            sreset_pulse  <= 1'b0;
            buf_idx       <= 17'd0;
            srow          <= FRAME_H[8:0] - 9'd1;   // 239
            scol          <= FRAME_W[8:0] - 9'd1;   // 319
            frame_we      <= 1'b0;
            frame_waddr   <= 16'd0;
            frame_wdata   <= 16'd0;
            dec_we        <= 1'b0;
            dec_waddr     <= 13'd0;
            dec_wdata     <= 8'd0;
            for (di = 0; di < DEC_W; di = di + 1)
                dacc[di] <= 12'd0;
        end else begin
            s_axi_awready <= 1'b0;
            s_axi_wready  <= 1'b0;
            sreset_pulse  <= 1'b0;
            frame_we      <= 1'b0;
            dec_we        <= 1'b0;

            // Command flags consumed by track_ctrl
            if (start_consume) start_pend <= 1'b0;
            if (tinit_consume) tinit_pend <= 1'b0;

            // IRQ set (from track_ctrl result pulse)
            if (irq_set) irq_pending <= 1'b1;

            if (s_axi_bvalid && s_axi_bready)
                s_axi_bvalid <= 1'b0;

            if (s_axi_awvalid && !aw_pend && !s_axi_bvalid) begin
                aw_addr_lat   <= s_axi_awaddr;
                aw_pend       <= 1'b1;
                s_axi_awready <= 1'b1;
            end

            if (s_axi_wvalid && !w_pend && !s_axi_bvalid) begin
                w_data_lat   <= s_axi_wdata;
                w_pend       <= 1'b1;
                s_axi_wready <= 1'b1;
            end

            if (aw_pend && w_pend && !s_axi_bvalid) begin
                aw_pend      <= 1'b0;
                w_pend       <= 1'b0;
                s_axi_bvalid <= 1'b1;
                s_axi_bresp  <= 2'b00;   // always OKAY

                case (aw_addr_lat[5:2])

                    REG_CTRL: begin
                        if (w_data_lat[0]) start_pend <= 1'b1;
                        if (w_data_lat[2]) tinit_pend <= 1'b1;
                        if (w_data_lat[1]) begin
                            sreset_pulse <= 1'b1;
                            start_pend   <= 1'b0;
                            tinit_pend   <= 1'b0;
                        end
                    end

                    REG_MODE:       mode       <= w_data_lat[1:0];
                    REG_THRESH:     thresh     <= w_data_lat[DATA_WIDTH-1:0];
                    REG_KCF_THRESH: kcf_thresh <= w_data_lat[DATA_WIDTH-1:0];
                    REG_LAMBDA:     lambda     <= w_data_lat[DATA_WIDTH-1:0];
                    REG_IRQ_MASK:   irq_mask   <= w_data_lat[0];

                    REG_IRQ_STAT:
                        if (w_data_lat[0] && !irq_set) irq_pending <= 1'b0;

                    // ── RGB565 pixel upload (2 pixels / write) ─────────
                    REG_IMAGE_FRM: begin
                        if (pix_accept) begin
                            // Converted pair → one descending 16-bit word
                            // (this is the hardware un-flip)
                            frame_we    <= 1'b1;
                            frame_waddr <= wword_addr;
                            frame_wdata <= {wgray_a, wgray_b};
                            buf_idx     <= buf_idx + 17'd2;

                            // On-the-fly decimation.  Scan is bottom-up,
                            // right-to-left: a 4×4 block completes on its
                            // LAST-arriving row (srow%4==0) and last pair
                            // (scol%4==1).
                            if (srow[1:0] == 2'd0 && scol[1:0] == 2'd1) begin
                                dec_we    <= 1'b1;
                                dec_waddr <= wdec_addr;
                                dec_wdata <= (({2'd0, dacc[wbc]} + {4'd0, wsum2})
                                              >> 4);
                                dacc[wbc] <= 12'd0;
                            end else begin
                                dacc[wbc] <= dacc[wbc] + {2'd0, wsum2};
                            end

                            // Advance descending position
                            if (scol == 9'd1) begin
                                scol <= FRAME_W[8:0] - 9'd1;   // 319
                                srow <= srow - 9'd1;
                            end else begin
                                scol <= scol - 9'd2;
                            end
                        end
                        // else: ACKed OKAY, silently discarded (ICD rule)
                    end

                    REG_TARGET_POS: begin
                        target_row <= w_data_lat[8:0];
                        target_col <= w_data_lat[24:16];
                    end

                    // ── BUF_IDX: reset/seek (0 and 76800 supported) ────
                    REG_BUF_IDX: begin
                        buf_idx <= w_data_lat[16:0];
                        srow    <= FRAME_H[8:0] - 9'd1;
                        scol    <= FRAME_W[8:0] - 9'd1;
                        for (di = 0; di < DEC_W; di = di + 1)
                            dacc[di] <= 12'd0;
                    end

                    // 0x34–0x3C reserved + read-only regs: ACK and ignore
                    default: ;

                endcase
            end
        end
    end

endmodule
