`timescale 1ns/1ps
// =============================================================================
// tb_image_ip_axilite.sv  —  ICD v3 verification (AXI4-Lite only)
//
// Emulates the real camera: 320×240 RGB565, 2 bytes/pixel HIGH byte first,
// sensor flip+mirror → stream arrives BOTTOM-RIGHT first.  Two RGB565
// pixels per 32-bit IMAGE_FRAME write; the IP converts to grayscale and
// un-flips in hardware.  All TB coordinates are UPRIGHT-frame.
//
// Scenario (synthetic 8×8 bright ball on a dark background):
//   A. Reset → KCF self-init → configure (AUTO, THRESH, poll mode).
//   B. Designation: FULL camera-order AXI upload, ball at (120,160) →
//      TARGET_POS → CTRL.target_init → poll done.
//   C. Frame 1, ball at (128,152): full AXI upload → acquisition: NCC finds
//      the ball, in-frame switch to KCF (algo=KCF, tracking=1), ABS ±4.
//   D. Frame 2, ball at (134,146): backdoor-loaded → KCF-only, ABS follows.
//   E. KCF_THRESH=3, then 3 blank frames → tracking drops; frame 4 = NCC.
//   F. Protocol checks: BUF_IDX=76,800, saturation discard, busy-drop,
//      write-only/reserved reads 0.
// =============================================================================

module tb_image_ip_axilite;

    parameter FRAME_W  = 320;
    parameter FRAME_H  = 240;
    parameter PATCH_N  = 64;
    parameter DEC      = 4;
    localparam FRAME_PIXELS = FRAME_W*FRAME_H;    // 76,800
    localparam FRAME_WORDS  = FRAME_PIXELS/2;     // 38,400
    localparam DEC_W        = FRAME_W/DEC;        // 80
    localparam DEC_H        = FRAME_H/DEC;        // 60

    reg clk = 0, rst_n = 0;
    always #10 clk = ~clk;   // 50 MHz

    // AXI4-Lite master
    reg  [31:0] s_axi_awaddr = 0;
    reg         s_axi_awvalid = 0;
    wire        s_axi_awready;
    reg  [31:0] s_axi_wdata = 0;
    reg  [3:0]  s_axi_wstrb = 4'hF;
    reg         s_axi_wvalid = 0;
    wire        s_axi_wready;
    wire [1:0]  s_axi_bresp;
    wire        s_axi_bvalid;
    reg         s_axi_bready = 1;
    reg  [31:0] s_axi_araddr = 0;
    reg         s_axi_arvalid = 0;
    wire        s_axi_arready;
    wire [31:0] s_axi_rdata;
    wire [1:0]  s_axi_rresp;
    wire        s_axi_rvalid;
    reg         s_axi_rready = 1;
    wire        irq_out;

    image_ip_axilite #(
        .FRAME_W(FRAME_W), .FRAME_H(FRAME_H), .PATCH_N(PATCH_N), .DEC(DEC),
        // Synthetic preloaded designation frame (ball at (120,160)) —
        // generated by: python scripts/gen_target_mem.py --synthetic
        .TARGET_MEM("tb_target_frame.mem"),
        .TGT_ROW(9'd120), .TGT_COL(9'd160),
        .AUTO_TINIT(1), .NCC_STRIDE(2)
    ) dut (
        .clk(clk), .rst_n(rst_n),
        .s_axi_awaddr(s_axi_awaddr), .s_axi_awvalid(s_axi_awvalid),
        .s_axi_awready(s_axi_awready),
        .s_axi_wdata(s_axi_wdata), .s_axi_wstrb(s_axi_wstrb),
        .s_axi_wvalid(s_axi_wvalid), .s_axi_wready(s_axi_wready),
        .s_axi_bresp(s_axi_bresp), .s_axi_bvalid(s_axi_bvalid),
        .s_axi_bready(s_axi_bready),
        .s_axi_araddr(s_axi_araddr), .s_axi_arvalid(s_axi_arvalid),
        .s_axi_arready(s_axi_arready),
        .s_axi_rdata(s_axi_rdata), .s_axi_rresp(s_axi_rresp),
        .s_axi_rvalid(s_axi_rvalid), .s_axi_rready(s_axi_rready),
        .irq_out(irq_out)
    );

    integer errors = 0;

    // TB-side images: RGB565 (what the camera sends) + expected gray
    reg [15:0] img_rgb  [0:FRAME_PIXELS-1];   // upright indexing
    reg [7:0]  img_gray [0:FRAME_PIXELS-1];   // = luma(img_rgb), upright

    // ── Helpers mirroring the RTL exactly ───────────────────────────────
    function [15:0] rgb565_of_gray;           // gray → nearest RGB565
        input [7:0] g;
        begin
            rgb565_of_gray = {g[7:3], g[7:2], g[7:3]};
        end
    endfunction

    function [7:0] luma;                      // mirrors frame_input_if
        input [15:0] px;
        reg [7:0] r8, g8, b8;
        reg [15:0] acc;
        begin
            r8 = {px[15:11], px[15:13]};
            g8 = {px[10:5],  px[10:9]};
            b8 = {px[4:0],   px[4:2]};
            acc = 8'd77*r8 + 8'd150*g8 + 8'd29*b8;
            luma = acc[15:8];
        end
    endfunction

    // ── Synthetic frame: dark background + 8×8 bright ball at (cr, cc) ──
    task build_frame;
        input integer cr;
        input integer cc;
        input integer with_ball;
        integer r, c, i;
        reg [15:0] px;
        begin
            for (r = 0; r < FRAME_H; r = r + 1)
                for (c = 0; c < FRAME_W; c = c + 1) begin
                    i = r*FRAME_W + c;
                    if (with_ball &&
                        r >= cr-4 && r <= cr+3 && c >= cc-4 && c <= cc+3)
                        px = rgb565_of_gray(8'hF0);
                    else
                        px = rgb565_of_gray(8'h18);
                    img_rgb[i]  = px;
                    img_gray[i] = luma(px);
                end
        end
    endtask

    // ── AXI-Lite write / read ───────────────────────────────────────────
    task axi_write;
        input [31:0] addr;
        input [31:0] data;
        begin
            @(posedge clk); #1;
            s_axi_awaddr  = addr;
            s_axi_awvalid = 1;
            s_axi_wdata   = data;
            s_axi_wvalid  = 1;
            fork
                begin : aw_hs
                    while (!(s_axi_awvalid && s_axi_awready)) @(posedge clk);
                    #1 s_axi_awvalid = 0;
                end
                begin : w_hs
                    while (!(s_axi_wvalid && s_axi_wready)) @(posedge clk);
                    #1 s_axi_wvalid = 0;
                end
            join
            while (!s_axi_bvalid) @(posedge clk);
            @(posedge clk); #1;
        end
    endtask

    reg [31:0] rd_val;
    task axi_read;
        input [31:0] addr;
        begin
            @(posedge clk); #1;
            s_axi_araddr  = addr;
            s_axi_arvalid = 1;
            while (!s_axi_rvalid) @(posedge clk);
            rd_val = s_axi_rdata;
            #1 s_axi_arvalid = 0;
            @(posedge clk); #1;
        end
    endtask

    // ── Full camera-order AXI upload (38,400 packed RGB565 writes) ─────
    // Stream pixel k = upright index (76,799 − k); beat j sends stream
    // pixels 2j (first) and 2j+1.  Word layout: bytes H0 L0 H1 L1.
    task upload_frame_axi;
        integer j;
        reg [15:0] px_a, px_b;
        begin
            axi_write(32'h30, 32'd0);   // BUF_IDX = 0
            for (j = 0; j < FRAME_WORDS; j = j + 1) begin
                px_a = img_rgb[FRAME_PIXELS-1 - 2*j];     // first (odd idx)
                px_b = img_rgb[FRAME_PIXELS-2 - 2*j];     // second (even idx)
                axi_write(32'h28, {px_b[7:0], px_b[15:8],
                                   px_a[7:0], px_a[15:8]});
            end
        end
    endtask

    // ── Backdoor load: fill gray BRAMs directly, then BUF_IDX=76800 ────
    task upload_frame_backdoor;
        integer w, dr, dc, i, j;
        integer acc;
        begin
            for (w = 0; w < FRAME_WORDS; w = w + 1)
                dut.u_input.frame_buf[w] = {img_gray[2*w+1], img_gray[2*w]};
            for (dr = 0; dr < DEC_H; dr = dr + 1)
                for (dc = 0; dc < DEC_W; dc = dc + 1) begin
                    acc = 0;
                    for (i = 0; i < DEC; i = i + 1)
                        for (j = 0; j < DEC; j = j + 1)
                            acc = acc + img_gray[(dr*DEC+i)*FRAME_W + (dc*DEC+j)];
                    dut.u_input.dec_buf[dr*DEC_W + dc] = acc / 16;
                end
            axi_write(32'h30, 32'd76800);   // mark frame complete
        end
    endtask

    // ── Run one detection and read results ─────────────────────────────
    reg [31:0] r_status, r_row, r_col, r_conf;
    task run_detect;
        begin
            axi_write(32'h00, 32'h0000_0001);   // CTRL.start
            rd_val = 0;
            while (!rd_val[1]) axi_read(32'h10);
            r_status = rd_val;
            axi_read(32'h14); r_row  = rd_val;
            axi_read(32'h18); r_col  = rd_val;
            axi_read(32'h1C); r_conf = rd_val;
        end
    endtask

    function integer iabs;
        input integer v;
        begin iabs = (v < 0) ? -v : v; end
    endfunction

    // NCC acquisition cycle counter (counts clocks while the search runs)
    integer ncc_cycles = 0;
    always @(posedge clk) if (dut.u_ncc.busy) ncc_cycles = ncc_cycles + 1;

    initial begin
        rst_n = 0;
        #100;
        rst_n = 1;

        // ── A. Init ─────────────────────────────────────────────────────
        $display("Waiting for KCF Y_hat self-init...");
        @(posedge dut.u_kcf.init_done);
        $display("KCF init done.");

        axi_write(32'h04, 32'h0000_0000);   // MODE = AUTO
        axi_write(32'h08, 32'h0000_0040);   // THRESH = 0.25 (Q8.8, NCC² scale)
        axi_write(32'h0C, 32'h0000_0001);   // LAMBDA
        axi_write(32'h20, 32'h0000_0000);   // IRQ masked (poll mode)
        // KCF_THRESH stays at reset 0 → loss fallback disabled during tracking

        // Rule checks: write-only / reserved reads
        axi_read(32'h00);
        if (rd_val !== 0) begin errors = errors + 1;
            $display("FAIL: CTRL read = 0x%08x, expected 0", rd_val); end
        axi_read(32'h28);
        if (rd_val !== 0) begin errors = errors + 1;
            $display("FAIL: IMAGE_FRAME read = 0x%08x, expected 0", rd_val); end
        axi_read(32'h38);
        if (rd_val !== 0) begin errors = errors + 1;
            $display("FAIL: reserved 0x38 read = 0x%08x, expected 0", rd_val); end

        // ── B. Boot auto-designation from the PRELOADED frame ───────────
        // No runtime designation upload: the frame BRAM is bitstream-
        // initialised (tb_target_frame.mem, ball at (120,160)) and the IP
        // self-runs target_init at boot.  Software just polls done.
        $display("Waiting for boot auto-designation (preloaded frame)...");
        rd_val = 0;
        while (!rd_val[1]) axi_read(32'h10);
        // TARGET_POS must read back the baked centre
        axi_read(32'h2C);
        if (rd_val !== {7'd0, 9'd160, 7'd0, 9'd120}) begin
            errors = errors + 1;
            $display("FAIL: TARGET_POS reset = 0x%08x, expected (120,160)", rd_val);
        end else
            $display("Boot designation complete (baked centre (120,160)).");

        // ── C. Frame 1: ball (128,152), full camera-order upload ────────
        $display("Frame 1: ball (128,152), full AXI upload + acquisition...");
        build_frame(128, 152, 1);
        upload_frame_axi;

        axi_read(32'h30);
        if (rd_val !== 32'd76800) begin
            errors = errors + 1;
            $display("FAIL: BUF_IDX after upload = %0d, expected 76800", rd_val);
        end else
            $display("BUF_IDX = 76800 after upload.");

        // Saturation: extra pixel write discarded
        axi_write(32'h28, 32'hFFFF_FFFF);
        axi_read(32'h30);
        if (rd_val !== 32'd76800) begin
            errors = errors + 1;
            $display("FAIL: saturated write advanced BUF_IDX to %0d", rd_val);
        end else
            $display("Saturation discard verified.");

        ncc_cycles = 0;
        run_detect;
        $display("NCC acquisition took %0d cycles = %0d us @ 50 MHz",
                 ncc_cycles, ncc_cycles / 50);

        $display("  STATUS=0x%02x  ABS=(%0d,%0d)  conf=%0d  algo=%0d  tracking=%0d",
                 r_status, r_row, r_col, $signed(r_conf),
                 r_status[3:2], r_status[4]);
        if (r_status[3:2] !== 2'd1) begin errors = errors + 1;
            $display("FAIL: expected algo=KCF after acquisition"); end
        if (r_status[4] !== 1'b1) begin errors = errors + 1;
            $display("FAIL: expected tracking=1"); end
        if (iabs(r_row - 128) > 4 || iabs(r_col - 152) > 4) begin
            errors = errors + 1;
            $display("FAIL: ABS off ball centre (128,152) by >4");
        end

        // Busy-drop check: pixel writes during a detection are discarded
        build_frame(134, 146, 1);
        upload_frame_backdoor;
        axi_write(32'h00, 32'h0000_0001);   // start frame 2 detection
        axi_write(32'h30, 32'd0);           // reset counter
        axi_write(32'h28, 32'h5555_5555);   // should be dropped (busy)
        axi_read(32'h30);
        if (rd_val !== 32'd0) begin
            errors = errors + 1;
            $display("FAIL: pixel write during busy advanced BUF_IDX to %0d", rd_val);
        end else
            $display("Busy-drop verified.");

        // ── D. Frame 2 results: KCF-only path, ball moved (+6,-6) ───────
        rd_val = 0;
        while (!rd_val[1]) axi_read(32'h10);
        r_status = rd_val;
        axi_read(32'h14); r_row = rd_val;
        axi_read(32'h18); r_col = rd_val;
        axi_read(32'h1C); r_conf = rd_val;
        $display("Frame 2: STATUS=0x%02x  ABS=(%0d,%0d)  conf=%0d",
                 r_status, r_row, r_col, $signed(r_conf));
        if (r_status[3:2] !== 2'd1) begin errors = errors + 1;
            $display("FAIL: frame 2 expected algo=KCF"); end
        if (iabs(r_row - 134) > 3 || iabs(r_col - 146) > 3) begin
            errors = errors + 1;
            $display("FAIL: frame 2 ABS off ball centre (134,146) by >3");
        end

        // ── E. Loss: enable KCF_THRESH, 3 blank frames → fallback ───────
        // Tracked-ball KCF confidence is ≈250 (Q8.8 ≈ 0.98); set the loss
        // threshold at 128 (0.5) so target-less crops count as losses.
        axi_write(32'h34, 32'h0000_0080);
        axi_read(32'h34);
        if ($signed(rd_val) !== 128) begin errors = errors + 1;
            $display("FAIL: KCF_THRESH readback = %0d, expected 128", rd_val); end

        $display("Loss test: 3 blank frames...");
        build_frame(0, 0, 0);
        begin : loss_loop
            integer lf;
            for (lf = 0; lf < 3; lf = lf + 1) begin
                upload_frame_backdoor;
                run_detect;
                $display("  blank frame %0d: algo=%0d conf=%0d tracking=%0d",
                         lf+1, r_status[3:2], $signed(r_conf), r_status[4]);
            end
        end
        if (r_status[4] !== 1'b0) begin
            errors = errors + 1;
            $display("FAIL: tracking still set after 3 low-confidence frames");
        end else
            $display("Tracking dropped after 3 low-confidence KCF frames.");

        // 4th frame: NCC re-acquisition path (blank → low conf, algo=NCC)
        upload_frame_backdoor;
        ncc_cycles = 0;
        run_detect;
        $display("  frame 4: algo=%0d conf=%0d  (NCC re-acq: %0d cycles = %0d us)",
                 r_status[3:2], $signed(r_conf), ncc_cycles, ncc_cycles / 50);
        if (r_status[3:2] !== 2'd0) begin
            errors = errors + 1;
            $display("FAIL: expected NCC re-acquisition (algo=0) after loss");
        end

        if (errors == 0)
            $display("\ntb_image_ip_axilite (ICD v3): ALL TESTS PASSED");
        else
            $display("\ntb_image_ip_axilite (ICD v3): %0d TEST(S) FAILED", errors);

        #200;
        $finish;
    end

    // Timeout watchdog
    initial begin
        #200_000_000;
        $display("TIMEOUT");
        $finish;
    end

endmodule
